// generateCypressTest.ts

import * as fs from 'fs';
import * as prettier from 'prettier';

/**
 * Step types that can be easily generated by a UI
 */
interface Step {
  type: string;
  [key: string]: any;
}

interface Scenario {
  name: string;
  description?: string;
  steps: Step[];
}

/**
 * Step generators - maps step types to Cypress code
 */
const stepGenerators: Record<string, (step: Step) => string> = {
  // Navigation
  navigate: (step) => `cy.visit('${step.url}');`,

  // Input actions
  fillInput: (step) => `cy.get('${step.selector}').type('${step.value}');`,
  clearInput: (step) => `cy.get('${step.selector}').clear();`,

  // Click actions
  click: (step) => `cy.get('${step.selector}').click();`,
  doubleClick: (step) => `cy.get('${step.selector}').dblclick();`,
  rightClick: (step) => `cy.get('${step.selector}').rightclick();`,

  // Select/Checkbox actions
  select: (step) => `cy.get('${step.selector}').select('${step.value}');`,
  check: (step) => `cy.get('${step.selector}').check();`,
  uncheck: (step) => `cy.get('${step.selector}').uncheck();`,

  // Wait actions
  wait: (step) => `cy.wait(${step.milliseconds});`,
  waitForSelector: (step) => `cy.get('${step.selector}', { timeout: ${step.timeout || 10000} });`,

  // Visibility assertions
  assertVisible: (step) => `cy.get('${step.selector}').should('be.visible');`,
  assertHidden: (step) => `cy.get('${step.selector}').should('not.be.visible');`,
  assertExists: (step) => `cy.get('${step.selector}').should('exist');`,
  assertNotExists: (step) => `cy.get('${step.selector}').should('not.exist');`,

  // Text assertions
  assertText: (step) => `cy.get('${step.selector}').should('contain.text', '${step.text}');`,
  assertExactText: (step) => `cy.get('${step.selector}').should('have.text', '${step.text}');`,
  assertValue: (step) => `cy.get('${step.selector}').should('have.value', '${step.value}');`,

  // State assertions
  assertEnabled: (step) => `cy.get('${step.selector}').should('not.be.disabled');`,
  assertDisabled: (step) => `cy.get('${step.selector}').should('be.disabled');`,
  assertChecked: (step) => `cy.get('${step.selector}').should('be.checked');`,
  assertUnchecked: (step) => `cy.get('${step.selector}').should('not.be.checked');`,
  assertFocused: (step) => `cy.get('${step.selector}').should('have.focus');`,

  // Attribute assertions
  assertAttribute: (step) => `cy.get('${step.selector}').should('have.attr', '${step.attribute}', '${step.value}');`,
  assertClass: (step) => `cy.get('${step.selector}').should('have.class', '${step.className}');`,
  assertCss: (step) => `cy.get('${step.selector}').should('have.css', '${step.property}', '${step.value}');`,

  // URL assertions
  assertUrl: (step) => `cy.url().should('eq', '${step.url}');`,
  assertUrlContains: (step) => `cy.url().should('include', '${step.text}');`,

  // Alert handling
  assertAlert: (step) => `cy.on('window:alert', (text) => { expect(text).to.equal('${step.text}'); });`,

  // Count assertions
  assertCount: (step) => `cy.get('${step.selector}').should('have.length', ${step.count});`,

  // Scroll actions
  scrollTo: (step) => `cy.get('${step.selector}').scrollIntoView();`,
  scrollToTop: () => `cy.scrollTo('top');`,
  scrollToBottom: () => `cy.scrollTo('bottom');`,

  // Screenshot
  screenshot: (step) => `cy.screenshot('${step.name || 'screenshot'}');`,

  // Custom Cypress command (for advanced users)
  custom: (step) => step.code,
};

/**
 * Validates that a step has a valid type and required parameters
 */
function validateStep(step: Step, index: number): void {
  if (!step.type) {
    throw new Error(`Step at index ${index} is missing a 'type' property`);
  }

  if (!stepGenerators[step.type]) {
    const availableTypes = Object.keys(stepGenerators).join(', ');
    throw new Error(
      `Step at index ${index} has invalid type '${step.type}'. Available types: ${availableTypes}`
    );
  }

  // Validate required parameters based on step type
  const requiredParams: Record<string, string[]> = {
    navigate: ['url'],
    fillInput: ['selector', 'value'],
    clearInput: ['selector'],
    click: ['selector'],
    doubleClick: ['selector'],
    rightClick: ['selector'],
    select: ['selector', 'value'],
    check: ['selector'],
    uncheck: ['selector'],
    wait: ['milliseconds'],
    waitForSelector: ['selector'],
    assertVisible: ['selector'],
    assertHidden: ['selector'],
    assertExists: ['selector'],
    assertNotExists: ['selector'],
    assertText: ['selector', 'text'],
    assertExactText: ['selector', 'text'],
    assertValue: ['selector', 'value'],
    assertEnabled: ['selector'],
    assertDisabled: ['selector'],
    assertChecked: ['selector'],
    assertUnchecked: ['selector'],
    assertFocused: ['selector'],
    assertAttribute: ['selector', 'attribute', 'value'],
    assertClass: ['selector', 'className'],
    assertCss: ['selector', 'property', 'value'],
    assertUrl: ['url'],
    assertUrlContains: ['text'],
    assertAlert: ['text'],
    assertCount: ['selector', 'count'],
    scrollTo: ['selector'],
    custom: ['code'],
  };

  const required = requiredParams[step.type] || [];
  for (const param of required) {
    if (step[param] === undefined || step[param] === null || step[param] === '') {
      throw new Error(
        `Step at index ${index} (type: '${step.type}') is missing required parameter '${param}'`
      );
    }
  }
}

/**
 * Validates the entire scenario
 */
function validateScenario(scenario: Scenario): void {
  if (!scenario.name) {
    throw new Error('Scenario must have a name');
  }

  if (!scenario.steps || !Array.isArray(scenario.steps)) {
    throw new Error('Scenario must have a steps array');
  }

  if (scenario.steps.length === 0) {
    throw new Error('Scenario must have at least one step');
  }

  scenario.steps.forEach((step, index) => validateStep(step, index));
}

/**
 * Generates Cypress code from a scenario
 */
function generateCypressTest(scenario: Scenario): string {
  validateScenario(scenario);

  const stepsCode = scenario.steps
    .map((step) => {
      const generator = stepGenerators[step.type];
      return `    ${generator(step)}`;
    })
    .join('\n');

  const description = scenario.description || scenario.name;

  return `/// <reference types="cypress" />

describe('${scenario.name}', () => {
  it('${description}', () => {
${stepsCode}
  });
});
`;
}

/**
 * Writes the generated test to a file
 */
function writeSpecFile(scenario: Scenario, outputPath: string): void {
  try {
    const cypressTestCode = generateCypressTest(scenario);
    const formattedCode = prettier.format(cypressTestCode, { parser: 'babel' });
    fs.writeFileSync(outputPath, formattedCode);
    console.log(`✓ Spec file successfully written to ${outputPath}`);
  } catch (error) {
    console.error(`✗ Error generating spec file: ${error.message}`);
    throw error;
  }
}

/**
 * Example scenario - this would be generated by a UI in production
 */
const scenario: Scenario = {
  name: 'User Login Flow',
  description: 'Test user can login with valid credentials',
  steps: [
    { type: 'navigate', url: 'http://example.com/login' },
    { type: 'fillInput', selector: '#username', value: 'testuser' },
    { type: 'fillInput', selector: '#password', value: 'password123' },
    { type: 'click', selector: '#login-button' },
    { type: 'assertUrl', url: 'http://example.com/dashboard' },
    { type: 'assertVisible', selector: '.welcome-message' },
    { type: 'assertText', selector: '.welcome-message', text: 'Welcome back, testuser!' },
  ],
};

// Generate the test
const outputPath = './cypress/integration/generated.spec.ts';
writeSpecFile(scenario, outputPath);

// Export for use as a module
export { Scenario, Step, generateCypressTest, writeSpecFile };
