// core/types.ts - Framework-agnostic types

/**
 * Step types that can be easily generated by a UI
 * These are framework-agnostic - they describe WHAT to do, not HOW
 */
export interface Step {
  type: string;
  thenSteps?: Step[];  // For if-then-else
  elseSteps?: Step[];  // For if-then-else
  [key: string]: any;  // Additional parameters based on step type
}

/**
 * A test scenario containing multiple steps
 */
export interface Scenario {
  name: string;
  description?: string;
  steps: Step[];
}

/**
 * Required parameters for each step type
 */
export const STEP_REQUIRED_PARAMS: Record<string, string[]> = {
  // Navigation
  navigate: ['url'],

  // Input actions
  fillInput: ['selector', 'value'],
  clearInput: ['selector'],

  // Click actions
  click: ['selector'],
  doubleClick: ['selector'],
  rightClick: ['selector'],

  // Select/Checkbox actions
  select: ['selector', 'value'],
  check: ['selector'],
  uncheck: ['selector'],

  // Wait actions
  wait: ['milliseconds'],
  waitForSelector: ['selector'],

  // Visibility assertions
  assertVisible: ['selector'],
  assertHidden: ['selector'],
  assertExists: ['selector'],
  assertNotExists: ['selector'],

  // Text assertions
  assertText: ['selector', 'text'],
  assertExactText: ['selector', 'text'],
  assertValue: ['selector', 'value'],

  // State assertions
  assertEnabled: ['selector'],
  assertDisabled: ['selector'],
  assertChecked: ['selector'],
  assertUnchecked: ['selector'],
  assertFocused: ['selector'],

  // Attribute assertions
  assertAttribute: ['selector', 'attribute', 'value'],
  assertClass: ['selector', 'className'],
  assertCss: ['selector', 'property', 'value'],

  // URL assertions
  assertUrl: ['url'],
  assertUrlContains: ['text'],

  // Alert handling
  assertAlert: ['text'],

  // Count assertions
  assertCount: ['selector', 'count'],

  // Scroll actions
  scrollTo: ['selector'],
  scrollToTop: [],
  scrollToBottom: [],

  // Screenshot
  screenshot: [],

  // Custom code
  custom: ['code'],

  // Conditionals
  ifExists: ['selector', 'thenSteps'],
  ifVisible: ['selector', 'thenSteps'],
  ifContainsText: ['selector', 'text', 'thenSteps'],
  ifUrlContains: ['text', 'thenSteps'],
  ifHasAttribute: ['selector', 'attribute', 'value', 'thenSteps'],
  ifHasClass: ['selector', 'className', 'thenSteps'],
};
